DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;
USE bd;

CREATE TABLE JUGADOR(
NOMBRE VARCHAR(50),
ID VARCHAR(10) NOT NULL,
PASSWORD VARCHAR(15) NOT NULL,
VICTORIAS INT,
CARRERINES INT, /*Carrerines son las carreras jugadas*/
WINRATE FLOAT = (VICTORIAS/CARRERINES)*100, 
CIRCUITOFAV VARCHAR(50), /*El más jugado por ese jugador*/
TIEMPOTOTALJUGADO VARCHAR(20),
PRIMARY KEY(ID)
)ENGINE=Inno DB;

CREATE TABLE CARRERIN(
ID1 VARCHAR(10) NOT NULL,
ID2 VARCHAR(10) NOT NULL,
DURACION VARCHAR(20),
GANADOR VARCHAR(50),
CIRCUITO VARCHAR(50),
VUELTARAPIDA VARCHAR (15),
PRIMARY KEY(ID)
)ENGINE = InnoDB; 

Create Table ListaDeCarrerines( /*Lista que contiene los carrerines de un circuito*/
CIRCUITO VARCHAR(50),   
CARRERINESTOTALES INTEGER NOT NULL,
IDMVP VARCHAR(20) NOT NULL,
JUGADORMASRAPIDO VARCHAR(15),
    FOREIGN KEY (IDMVP) REFERENCES JUGADOR(VICTORIAS)
	FOREIGN KEY (JUGADORMASRAPIDO) REFERENCES CARRERIN(VUELTARAPIDA) /*Haremos una función que compare las vueltas más rápidas de cada carrerin de la lista y nos de la más rápida*/
	)ENGINE = InnoDB;


INSERT INTO JUGADOR VALUES("Jofre", "JJJJ" , "UwU", 4, 15, "26,67", "GP EETAC");
INSERT INTO JUGADOR VALUES("Oriol", "OOOO", "Arigato", 1, 37, "2,7", "GP TORRE");
INSERT INTO JUGADOR VALUES("Victor", "VVVV", "Miau", 2, 10, "20", "GP BOCACRANK");

INSERT INTO CARRERIN VALUES("JJJJ","OOOO","20:33:04","JOFRE","GP EETAC","1:33:33");
INSERT INTO CARRERIN VALUES("VVVV","OOOO","15:23:01","JOFRE","GP TORRE","1:02:56");

INSERT INTO ListaDeCarrerines VALUES (20, "JJJJ", "1:02:56");
INSERT INTO ListaDeCarrerines VALUES (16, "OOOO", "1:21:01");
